### PR TITLE
Update scraper.py

### PR DESCRIPTION
**Pull request by dheeraj-rao-git**
This is Dheeraj Rao from internshala.

### CODE REVIEW

**Comment by KayvanShah1** [comment]
Please correctly name the PULL request and the assignment is partially done

**Review by KayvanShah1 — COMMENTED** [review]
It seems you haven't understood the problem statement. The message on Internshala doesn't sound appropriate because you have been putting efforts in the wrong direction.

The source you referring to offers provides time-series data available and accessible via multiple services. The approach you are currently using doesn't justify the purpose and you have taken a week figuring out the wrong thing and request for an extension of the deadline isn't well justified.

---
Try the below problem statement

**Source 7: PPP Philippines**
 ---
This is the official government site of the Philippines where its Public-Private Partnership projects are all listed.
 
The objective is to scrape the data and set up a proper flow for collecting and consuming the latest data and historical data.
The data to be scraped can be accessed from here: 
https://ppp.gov.ph/project-database/

**Comment by dheeraj-rao-git** [comment]
I apologise for the message on internshala. Let me check the problem statement and get back to you.
Thank you for your fastest response.

**Comment by KayvanShah1** [comment]
Closing the PULL request since there have been no significant changes in the last 2 days.

**Pull request closed without merging**
